= Ulquikit

*This project is being rewritten in Common Lisp for better performance,
maintenance and deployment.*

Literate programming is a term coined by professor
http://en.wikipedia.org/wiki/Donald_Knuth[Donald E. Knuth] in 1984, describing
a new way of **thinking and writing** computer programs.

In literate programming, writing a program

* is not writing code for computer to run,
* but words for other human beings to understand.

To quote prof. Knuth:

[quote, Donald E. Knuth, "Literate Programming (1984). CSLI, 1992, pg. 99."]
____
Let us change our traditional attitude to the construction of programs:
Instead of imagining that our main task is to instruct a computer what to do,
let us concentrate rather on explaining to human beings what we want a
computer to do.

The practitioner of literate programming can be regarded as an essayist, whose
main concern is with exposition and excellence of style. Such an author, with
thesaurus in hand, chooses the names of variables carefully and explains what
each variable means. He or she strives for a program that is comprehensible
because its concepts have been introduced in an order that is best for human
understanding, using a mixture of formal and informal methods that reinforce
each other.
____

In traditional way of programming, programmers *write code and supply
documentation*.  In literate programming, programmers *write documents and
supply code*.  Hence, it is not about generating beautiful documentation.

== Why literate programming?

* Perhaps you like
  http://doc.qt.io/qt-5/qtexamplesandtutorials.html[Qt-style tutorials]?

* As it enforces developers to think and explain before writing code, programs
  are generally more well-constructed and easier to understand.

* It encourages people to write high-quality programs. Every piece of thought
  ought to be expressed clearly, making design decisions obvious.

* Literate programming is a great help in *understanding, maintaining, and
  extending* programs.

* Bugs that start from designing and thinking process are easier to detect and
  fix.

== Why not literate programming?

* Harder to debug using traditional tools.

* Cannot apply rapid development (perhaps?).

* When you hate writing documentation.

== Why Ulquikit?

* Making literate programming fun and productive again.

* Using the excellent http://asciidoc.org[AsciiDoc] as the default markup
  language.  Why not Markdown?  AsciiDoc is more complete in every
  possible way.

* APIs are *designed for human being*.

* Easily hackable and extensible.

== Communication channels

* For announcements, please join
  https://groups.google.com/d/forum/ulquikit-announce[Ulquikit Announcement
  mailing list].

* For users and developers, should you have any questions or feedbacks, please
  https://github.com/cmpitg/ulquikit/issues[raise an issue on Github].

== Requirements

* Ruby 1.9.3+ with http://asciidoctor.org/[AsciiDoctor].

== License

This project is distributed under the terms of the GNU General Public
License v3.  See `COPYING` for further information.

== Contributors

Special thanks to:

* https://github.com/myguidingstar[@myguidingstar]
* https://github.com/lewtds[@lewtds]

== Copyright

Copyright 2013-2015 © Ha-Duong Nguyen <cmpitg AT gmailDOTcom>
