= Ulquikit

Ulquikit is written in literate programming itself with a small bootstrap
code.  This document contains everything about Ulquikit, from documentation to
full source code.

The best way to learn about Ulquikit is to start from this document, section
<<getting-started,Getting started>>

[[getting-started]]
== Getting started

NOTE: Unless specifically noted, all commands are executed in your project
root directory.

=== For users

[[project-structure]]
* Project structure:
+
Ulquikit makes use of a typical project structure:
+
----
project-name/
  generated-docs/  <1>
  generated-src/   <2>
  src/             <3>
    Main.adoc
  README.md
----
<1> generated documents
<2> generated source code
<3> your (literate) source code
+
Ulquikit could be used without making any change to your current project
structure.  By default, it detects literate source code with +.adoc+ or +.txt+
extension in +src/+ directory to produce corresponding documents and source
code.
+

* Generating source code:
+
Generated source code resides in +<project-root>/generated-src/+.
+
To generate source code:
+
[source,sh]
----
ulqui generate-src
----
+
You could also specify your own source and destination:
+
[source,sh]
----
# Uses literate source code from source/ and outputs to generated-source/
ulqui generate-src --from source --to generated-source
----

* Generating documents:
+
Generated documents reside in +<project-root>/generated-docs/+.
+
To generate documents:
+
[source,sh]
----
ulqui generate-docs
----
+
You could also specify your source and destination:
+
[source,sh]
----
# Uses literate source code from source/ and outputs to documents/
ulqui generate-docs --from source --to documents
----

=== For developers

== How it works

=== Requirements

* http://asciidoctor.org[AsciiDoctor]
* http://racket-lang.org[Racket]

=== In-depth

To generate docs and source code from this file, two Racket scripts are used:
+bootstrap/generate-docs.rkt+ and +bootstrap/generate-src.rkt+.  These 2 files
are very short and simple.  They do just one thing as their names suggest by:

* Looking for and save all AsciiDoc code blocks
  ** If a code block starts with +file::+ it's a file name
  ** If a code block starts with +snippet::+: it's a code chunk name
  ** Otherwise, ignore the code block.

* For each code block, looking for +;; include::<chunk-name>+ and replacing
  that line with the corresponding chunk.  Proper indentation is inserted.
  Invalid ++<chunk-name>++s are ignored.

* Finally, for each code block with file name, write its contents to the
  corresponding file.
