#
# This file is part of Ulquikit project.
#
# Copyright (C) 2013 Duong H. Nguyen <cmpitg AT gmailDOTcom>
#
# Ulquikit is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# Ulquikit is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# Ulquikit.  If not, see <http://www.gnu.org/licenses/>.
#
#
# References:
#    https://github.com/vmg/redcarpet
#

require_relative 'markdown_renderer'
require 'pygments'

sh 'mkdir -p scripts/ styles/ images/'

task :clean do
  sh 'rm -rf *.html'
end

task :nuke => [:clean] do
  sh 'rm -rf scripts/* styles/* images/*'
end

task :try do
  Renderer::render_file("main")
end

task :clean do
  sh 'rm -rf *.html'
end
