#
# This file is part of Ulquikit project.
#
# Copyright (C) 2013 Duong H. Nguyen <cmpitg AT gmailDOTcom>
#
# Ulquikit is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# Ulquikit is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# Ulquikit.  If not, see <http://www.gnu.org/licenses/>.
#
#
# References:
#    https://github.com/vmg/redcarpet
#

#
# Write docs:
# * Create a dir
# * Remove dirs recursively
# * Check if a file/dir exists
# * Functional-style apply method
# * Glob
#

require_relative 'bootstrap/markdown_renderer'
require 'pygments'

SOURCE_DIRS = %w[scripts/ styles/ images/]
BUILD_DIRS = %w[img/ js/ css/]

Dir.ensure_dirs *SOURCE_DIRS

task :clean do
  FileUtils.remove_paths *Dir.glob('*.html')
  FileUtils.remove_paths File.expand_path("../build")
end

task :nuke => [:clean] do
  # FileUtils.remove_paths *SOURCE_DIRS
  FileUtils.remove_paths *Dir.glob("styles/pygments.css")
end

task :try => [:gen_pygments_css] do
  BUILD_DIRS.each { |dir|
    Dir.ensure_dirs File.expand_path("../build/#{dir}")
  }
  Renderer::render_file "main"
end

task :gen_pygments_css do
  File.open('styles/pygments.css', 'w') { |file|
    # file.write Pygments.css(:style => "monokai")
    file.write Pygments.css
  }
end
